#!/usr/bin/env bash
# FitHub Deployment Quick Start
# Run this first to get everything working!

echo "🚀 FitHub Production Deployment Setup"
echo "======================================"
echo ""
echo "STEP 1: Prerequisites Check"
echo "  [ ] Git installed"
echo "  [ ] AWS CLI installed (https://aws.amazon.com/cli/)"
echo "  [ ] Terraform installed (https://www.terraform.io/downloads)"
echo "  [ ] Docker installed"
echo ""
echo "STEP 2: Run Setup Script"
echo "  $ cd fithub"
echo "  $ bash scripts/setup-github-actions.sh"
echo ""
echo "  This will:"
echo "  ✓ Create S3 state bucket"
echo "  ✓ Create DynamoDB lock table"
echo "  ✓ Create IAM user for GitHub"
echo "  ✓ Generate access keys"
echo ""
echo "STEP 3: Add GitHub Secrets"
echo "  1. Go to: GitHub Repo → Settings → Secrets and variables → Actions"
echo "  2. Create these secrets (from setup script output):"
echo "     • AWS_ACCESS_KEY_ID"
echo "     • AWS_SECRET_ACCESS_KEY"
echo "     • TF_STATE_BUCKET"
echo ""
echo "STEP 4: First Deployment"
echo "  $ git checkout -b feature/setup"
echo "  $ git push -u origin feature/setup"
echo "  1. Go to GitHub → Create PR to 'develop'"
echo "  2. GitHub Actions auto-tests and deploys to STAGING"
echo "  3. Merge to 'develop' (now live on staging)"
echo "  4. Create PR 'develop' → 'main'"
echo "  5. Get approval and merge"
echo "  6. Click 'Approve' in GitHub Actions"
echo "  7. GitHub auto-deploys to PRODUCTION 🎉"
echo ""
echo "WHAT YOU GET:"
echo "  ✅ Automatic testing on every commit"
echo "  ✅ Automatic Docker builds"
echo "  ✅ Auto-deploy to staging (instant)"
echo "  ✅ Auto-deploy to production (with approval)"
echo "  ✅ Automatic rollback on failures"
echo "  ✅ Health checks & monitoring"
echo "  ✅ Zero-downtime deployments"
echo ""
echo "MONITORING:"
echo "  Staging logs: aws logs tail /ecs/fithub-staging --follow"
echo "  Prod logs:    aws logs tail /ecs/fithub-production --follow"
echo "  Dashboard:    https://console.aws.amazon.com/ecs"
echo ""
echo "COSTS:"
echo "  Staging:     ~$50/month"
echo "  Production:  ~$190/month"
echo "  Total:       ~$240/month"
echo ""
echo "DOCS:"
echo "  Setup:    DEPLOYMENT.md"
echo "  Commands: DEPLOYMENT_QUICK_REFERENCE.md"
echo "  Overview: DEPLOYMENT_README.md"
echo ""
echo "======================================"
echo "Ready to deploy? Run:"
echo "  bash scripts/setup-github-actions.sh"
echo "======================================"
